from docutranslate.converter.x2md.converter_docling import ConverterDoclingConfig
from docutranslate.converter.x2md.converter_mineru import ConverterMineruConfig

x2md_convert_config_type=ConverterDoclingConfig | ConverterMineruConfig